### ISSUE TITLE
Validation of RAML is taking longer

### ISSUE THREAD

**Issue by unandyala** [aml-org/amf#718]
RAML validation with custom profile is talking longer. Please find the attached raml file and the profile used.
[checkout.zip](https://github.com/aml-org/amf/files/5490628/checkout.zip)
[profiles.zip](https://github.com/aml-org/amf/files/5490635/profiles.zip)

Code to validate
```javascript
import path from "path";
import * as amf from "amf-client-js";

async function validateRaml(): Promise<void> {
  amf.plugins.document.WebApi.register();
  amf.plugins.document.Vocabularies.register();
  amf.plugins.features.AMFValidation.register();
  await amf.AMF.init();
  const ramlFilePath = path.join(
    __dirname,
    "..",
    "..",
    "commerce-sdk",
    "apis",
    "checkout",
    "shopper-baskets",
    "shopper-baskets.raml"
  );
  const profilePath = path.join(
    __dirname,
    "..",
    "resources",
    "lint",
    "profiles",
    "mercury.raml"
  );

  const model = await new amf.Raml10Parser().parseFileAsync(
    `file://${path.resolve(ramlFilePath)}`
  );
  const profileName = await amf.Core.loadValidationProfile(
    `file://${profilePath}`
  );
  console.log(new Date(), "Starting validation");
  const results = await amf.Core.validate(
    model,
    profileName,
    amf.MessageStyles.RAML
  );
  console.log(new Date(), "Validation completed");
  if (results) {
    console.log(`Model: ${results.model}
                Profile: ${results.profile}
                Conforms? ${results.conforms}`);
  }
}

validateRaml().then((v) => {
  console.log("done!!");
});
```
With all the rules in the profile it is taking more than 2 mins to validate.
```
2020-11-04T21:03:18.091Z Starting validation
2020-11-04T21:05:54.258Z Validation completed
Model: shopper-baskets.raml
                Profile: mercury
                Conforms? true
done!!
```
With just one rule, it is taking more than 1 min to validate
```
2020-11-04T21:00:14.472Z Starting validation
2020-11-04T21:01:38.432Z Validation completed
Model: shopper-baskets.raml
                Profile: mercury
                Conforms? true
done!!
```
**Environment:**
  
  - AMF Version: 4.3.0
  - AMF Distribution: JS 
  - Operating System: macOS

**Comment by arielmirra** [comment]
Hi @unandyala! Thanks for submitting this issue. Could you please provide the previous AMF version in which the validations were faster (and maybe by how much)? That would really help. Thank you!

**Comment by unandyala** [comment]
We observed similar issues in 4.1.2 as well. We didn't track exactly when the issue started. It used to take a few seconds earlier not minutes

**Comment by arielmirra** [comment]
Hi @unandyala, I've been unable to reproduce the described behavior. In order to simplify version-changing and sync the javascript code being used, we've created this project:

[Custom Validations Test JS.zip](https://github.com/aml-org/amf/files/5554908/Custom.Validations.Test.JS.zip)

It runs AMFs' custom validations to a RAML file and outputs the result. The version of AMF can be easily changed in the `package.json` file. 

It would be great if you try to reproduce the issue in the same simplified context so we can pinpoint what the problem is and where it comes from. Thank you!

**Comment by unandyala** [comment]
Hi @arielmirra ,

I ran the code you provided against the attached raml and profile (attached in the first comment). And I am seeing similar results

Note: I just added `new Date()` for the log statements

```
~/Downloads/javascript$ node index.js                                                                                                                                                                                             
2020-11-20T02:35:04.206Z Parsing...
2020-11-20T02:35:05.478Z Resolving...
2020-11-20T02:35:06.874Z Validating...
2020-11-20T02:37:24.647Z Report: Model: amf://id
Profile: mercury
Conforms? true
Number of results: 0
```

**Comment by tomsfernandez** [comment]
Hi @unandyala, which Node version are you using to run this?

**Comment by unandyala** [comment]
Hi @tomsfernandez 
Node version is v12.16.3

**Comment by tomsfernandez** [comment]
@unandyala, I tested your api/profile with 4.2.0, 4.3.0, 4.4.0 and 4.5.0 and in all of those the execution time has been above the 2 minutes.

I created the internal ticket: https://www.mulesoft.org/jira/browse/APIMF-2711 to figure out why the validation is taking so long.

**Comment by unandyala** [comment]
Thanks for the update

**Comment by unandyala** [comment]
Hi @tomsfernandez,

The issue seems to have resolved in version 4.7.0. I ran the same code provided in https://github.com/aml-org/amf/issues/718#issuecomment-729059813 with the amf version 4.7.0. 

Looking at the results, there is not a huge improvement in the performance. Just want to check if this is expected.

Thanks
Ujwala

```
 ~/Downloads/javascript  node index.js                                   
2021-02-10T14:59:44.188Z Parsing...
2021-02-10T14:59:46.135Z Resolving...
2021-02-10T14:59:48.225Z Validating...
2021-02-10T15:02:32.845Z Report: Model: amf://id
Profile: mercury
Conforms? true
Number of results: 0
```

**Comment by looseale** [comment]
Hi @unandyala,
I don't know why this is closed, I will reopen it. 
I closed the issue from AMF side but I created a subtask to fix this problem. 
The performance issue is related with the use of the `extends` in the validation profile, so I create another issue to check the RAML validation profile that we provide.
I think I will fix this in the next days, so it will be released in the next release.
As a temporal workaround, you could delete the `extends: RAML` from your validation profile and validate the base RAML validation directly. Something like this:
```
  console.log(new Date(), "Starting validation");
  // First validate the API against the common RAML validations
  const baseResults = await amf.Core.validate(
    model,
    amf.ProfileNames.RAML,
    amf.MessageStyles.RAML
  );
  // Then with the custom profile (without the 'extends: RAML')
  const customResults = await amf.Core.validate(
    model,
    profileName,
    amf.MessageStyles.RAML
  );
  console.log(new Date(), "Validation completed");
```
The problem there is that you will have 2 ValidationReport (one for the regular RAML validations, another for your custom profile), but you can merge the list of results in one.

**Comment by unandyala** [comment]
Hi @looseale,
Any update on this ticket? We are also seeing memory issues with large RAMLs. Could this be related to the same issue?

Below are the error details. Please let me know if you would like me to create a separate ticket/issue for this

Thanks
Ujwala

```
npx @commerce-apps/raml-toolkit --profile mercury raml/shopper-baskets.raml raml/shopper-baskets-traits.raml

 10:39:38  + docker run -v /var/run/docker.sock:/var/run/docker.sock -e NODE_OPTIONS=--max-old-space-size=4096 --rm -iv /build/workspace/cc-mercury_Publish_API_master/anypoint-api:/raml:ro node:12-alpine npx @commerce-apps/raml-toolkit --profile mercury raml/shopper-baskets.raml raml/shopper-baskets-traits.raml
10:39:38  Unable to find image 'node:12-alpine' locally
10:39:44  Status: Downloaded newer image for node:12-alpine
10:40:40  Using built in profile: mercury
10:40:40  Using built in profile: mercury
10:40:40  Model: file:///raml/shopper-baskets-traits.raml
10:40:40  Profile: mercury
10:40:40  Conforms? true
10:40:40  Number of results: 0
10:40:40  Number of hidden warnings: 0
10:40:40      
10:43:46  
10:43:46  <--- Last few GCs --->
10:43:46  
10:43:46  [1:0x55ea9d449460]   223879 ms: Mark-sweep 4091.3 (4102.6) -> 4090.6 (4102.1) MB, 1864.4 / 0.0 ms  (average mu = 0.107, current mu = 0.000) allocation failure scavenge might not succeed
10:43:46  [1:0x55ea9d449460]   225578 ms: Mark-sweep 4091.6 (4102.1) -> 4090.6 (4102.3) MB, 1697.0 / 0.0 ms  (average mu = 0.055, current mu = 0.001) allocation failure scavenge might not succeed
10:43:46  
10:43:46  
10:43:46  <--- JS stacktrace --->
10:43:46  
10:43:46  ==== JS stack trace =========================================
10:43:46  
10:43:46      0: ExitFrame [pc: 0x55ea9b5ca0d9]
10:43:46  Security context: 0x269451bc08d1 <JSObject>
10:43:46      1: _findInIndex [0x293053231891] [/root/.npm/_npx/1/lib/node_modules/@commerce-apps/raml-toolkit/node_modules/n3/lib/N3Store.js:~101] [pc=0x15b09a5086c5](this=0x3458a2b84161 <N3Store map = 0x3f3c18ec65b9>,0x30f782eb6fd9 <Object map = 0x3290c7f40439>,0x30ef03c401b9 <null>,0x30ef03c401b9 <null>,0x30ef03c401b9 <null>,0x257698389331 <String[#7]: subject>,0x3...
10:43:46  
10:43:46  FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
[Pipeline] error
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // dir
[Pipeline] echo
10:44:08  ERROR - Caught Exception
10:44:08  hudson.AbortException: Aborting due to failed linting
[Pipeline] sh
10:44:08  + docker network rm net_7fd9931e-7346-4880-a25f-e0cab52788f4
10:44:08  net_7fd9931e-7346-4880-a25f-e0cab52788f4
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // wrap
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: ABORTED
REST API

```

**Comment by looseale** [comment]
Hi @unandyala.

We found that we have an incompatibility between SHACL and some of our internal validations for specs, so we need to make a big refactor there. In the meantime, I recommend you to use the workaround that I provided in a previous comment: remove the 'extends: RAML' of the profile and run the RAML validation directly using AMF first and then call the validation of the custom validations.

About the memory consumption problem: if removing the 'extends: RAML' from the profile fixes the problem, it could be related with this incompatible validations. If not, I think is a different problem.
In this area already have some pending optimizations in the way that the validations are generated, but they are not planned to be implemented in the short term. Also, if the API is very big (megabytes of size), the resulting model could be very big and the graph in memory could be heavy.

**Comment by gkhunger-sf** [comment]
Hi @looseale 

Thank you for looking into the issue and providing more details. We split the validations and that did lead to some good performance improvement but we were still seeing some really high memory consumption. During our investigation we found that most of that is due to the one rule we have in our custom profile which contains a SPARQL query. The rule is to check for duplicate display names in a raml. We have disabled that for now and that has led to some significant performance improvement. However, that rule is an important rule and we would really like to enable it back soon. Can you please help us re-write that rule so that it doesn't consume a ton of memory?

**Comment by looseale** [comment]
Hi @gkhunger-sf 
Could you please report it in another github issue? The profile attached here is old, it has the rule in JS not in SPARQL.
If I remember correctly, the rule checked the name of each domainElement versus the other domainElement names. In a very big API that could end in a lot of comparisons... I don't think there is a way to "cache" the names like in the JS rule in SPARQL (we are no experts in SPARQL, we only provide an interface to use it), but we could check if there is any optimization in our code that we could add.
In the future our plan is to check if this feature needs a performance enhancement, as right now we are working on refactoring the bases of AMF so we can work in this type of things more efficiently.

**Comment by gutee** [comment]
Old issue. Closing.
